name: common_code
description: 'A new Flutter package project.'
version: 0.0.1
homepage: ''

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.2

  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  calendar_date_picker2: ^1.1.5

  nested: ^1.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3

  flutter_svg: ^2.0.10
  get_it: ^7.7.0
  fpdart: ^1.1.0
  equatable: ^2.0.5
  dio: ^5.5.0
  google_sign_in: ^6.2.1

  loading_indicator: ^3.1.1

  auto_route: ^8.2.0
  # go_router: ^14.2.0

  internet_connection_checker: ^1.0.0
  connectivity_plus: ^6.0.3

  firebase_crashlytics: ^4.0.3
  firebase_core: ^3.2.0

  awesome_notifications: ^0.9.3
  fluttertoast: ^8.2.6

  logger: ^2.3.0
  signalr_netcore: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11

  flutter_lints: ^3.0.0

  json_serializable: ^6.8.0
  freezed: ^2.5.2 # analyzer: 6.5.1 > meta: 1.15.0

flutter:
