targets:
  $default:
    builders:
      freezed:
        options:
          when: false
          maybe_when: false
          when_map: false
          maybe_when_map: false
          map:
            maybe_map: false
    sources:
      - lib/**
      - pubspec.*
      - $package$
    dependencies:
      - :common_code

  common_code:
    sources:
      - common_code/lib/**
