name: yumi
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.9+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  auto_route: ^7.8.4
  flutter_svg: ^2.0.10+1
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  loading_indicator: ^3.1.1
  image_picker: ^1.0.7
  wakelock_plus: ^1.1.4
  flutter_rating_bar: ^4.0.1
  card_swiper: ^3.0.1
  calendar_date_picker2: ^0.5.5
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  url_launcher: ^6.2.5
  google_sign_in: ^6.2.1

  google_maps_flutter: ^2.2.8
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.8

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  path_provider: ^2.1.2
  # vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8

  json_serializable: ^6.7.1
  freezed: ^2.4.7

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/map/
    - assets/images/flow/
    - assets/images/registeration/

  fonts:
    - family: Inter
      fonts:
        - asset: 'fonts/Inter/static/Inter-Medium.ttf'
        - asset: 'fonts/Inter/static/Inter-Light.ttf'
          weight: 300
        - asset: 'fonts/Inter/static/Inter-Bold.ttf'
          weight: 700

  #

flutter_intl:
  enabled: true
