name: yumi
description: 'Food For Health.'

publish_to: 'none'

version: 2.0.1+10

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  nested: ^1.0.0
  equatable: ^2.0.5
  auto_route: ^8.2.0
  flutter_svg: ^2.0.10
  dio: ^5.5.0
  shared_preferences: ^2.2.3
  loading_indicator: ^3.1.1
  image_picker: ^1.1.2
  wakelock_plus: ^1.2.5
  flutter_rating_bar: ^4.0.1
  card_swiper: ^3.0.1
  calendar_date_picker2: ^1.1.5
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  url_launcher: ^6.3.0

  intl: ^0.19.0

  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1

  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.8

  permission_handler: ^11.3.1
  # flutter_local_notifications: ^17.1.2
  awesome_notifications: ^0.9.3
  fluttertoast: ^8.2.6

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.2

  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.0
  # vibration: ^1.8.4

  firebase_crashlytics: ^4.0.2
  firebase_core: ^3.1.1

  uuid: ^3.0.7
  logger: ^2.3.0
  signalr_netcore: ^1.3.7

  collection: ^1.18.0
  get_it: ^7.7.0
  fpdart: ^1.1.0
  skeletonizer: ^1.3.0
  mime: ^1.0.5
  package_info_plus: ^8.0.0
  # either_dart: ^1.0.0
  # hive: ^2.2.3
  # easy_localization: ^3.0.5
  # go_router: ^13.2.4

  internet_connection_checker: ^1.0.0
  connectivity_plus: ^6.0.3
  flutter_stripe: ^10.2.0

dev_dependencies:
  test: ^1.25.2 # test_api: 0.7.0
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11

  json_serializable: ^6.8.0
  freezed: ^2.5.2 # analyzer: 6.5.1 > meta: 1.15.0

  # mockito: ^5.4.4
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/map/
    - assets/images/flow/
    - assets/images/registeration/

  fonts:
    - family: Inter
      fonts:
        - asset: 'fonts/Inter/static/Inter-Medium.ttf'
        - asset: 'fonts/Inter/static/Inter-Light.ttf'
          weight: 300
        - asset: 'fonts/Inter/static/Inter-Bold.ttf'
          weight: 700

flutter_intl:
  enabled: true

flutter_native_splash:
  background_image: 'assets/splash/splash_light.png'

  image: assets/splash/logo_splash.png

  android_12:
    image: assets/splash/logo_splash_x.png
    background_image: 'assets/splash/splash_light.png'

  web: false
