name: dependencies
description: 'A new Flutter package project.'
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  image: ^4.2.0
  mime: ^1.0.5
  image_picker: ^1.1.2

  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.8

  wakelock_plus: ^1.2.5
  flutter_rating_bar: ^4.0.1
  card_swiper: ^3.0.1
  calendar_date_picker2: ^1.1.5

  nested: ^1.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3

  json_annotation: ^4.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.2
  equatable: ^2.0.5

  flutter_svg: ^2.0.10
  dio: ^5.5.0
  fpdart: ^1.1.0
  logger: ^2.3.0
  signalr_netcore: ^1.3.7

  uuid: ^3.0.7
  collection: ^1.18.0
  package_info_plus: ^8.0.0
  hotkey_manager: ^0.2.3

  get_it: ^7.7.0
  # google_sign_in: ^6.2.1
  # flutter_facebook_auth: ^7.0.1

  loading_indicator: ^3.1.1

  auto_route: ^8.2.0

  internet_connection_checker: ^1.0.0
  connectivity_plus: ^6.0.3

  firebase_crashlytics: ^4.0.3
  firebase_core: ^3.2.0

  awesome_notifications: ^0.9.3
  fluttertoast: ^8.2.6

  path_provider: ^2.1.3

  intl: ^0.19.0

  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

  flutter_stripe: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
# flutter:
