// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlhKSqJ_5FgfUS3tnGmjV6hxPocuFBB_Y',
    appId: '1:369476238484:android:3f5301c1fb5667b9178881',
    messagingSenderId: '369476238484',
    projectId: 'fir-computers-ip',
    databaseURL: 'https://fir-computers-ip.firebaseio.com',
    storageBucket: 'fir-computers-ip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnZo-_3VcwecWl6t8T_Gozht6Myt85Mhg',
    appId: '1:369476238484:ios:93603ab9ce6041c7178881',
    messagingSenderId: '369476238484',
    projectId: 'fir-computers-ip',
    databaseURL: 'https://fir-computers-ip.firebaseio.com',
    storageBucket: 'fir-computers-ip.appspot.com',
    iosClientId: '369476238484-ht3st1jc9l4gqgjm5dkn3g818403ve02.apps.googleusercontent.com',
    iosBundleId: 'com.yumi.yumi',
  );
}
